// The mark of a generated file: with it sync recognizes its own files and tells them from the
// human's.

/** Mark of a generated file: sync overwrites and deletes such a file itself. */
export const GENERATED_MARK = "Generated by `cyberzavod sync`";

/** Russian mark of versions before 0.8.0: sync recognizes its files in connected projects by it. */
export const LEGACY_GENERATED_MARK = "Сгенерировано `cyberzavod sync`";

const GENERATED_NOTE =
  "from harness and .cyberzavod/project.json: do not edit by hand. Project rules live in AGENTS.md.";

/** Mark line for a Markdown file: an HTML comment. */
export const MARKDOWN_GENERATED_COMMENT = `<!-- ${GENERATED_MARK} ${GENERATED_NOTE} -->`;

/** Mark line for a TOML or YAML file: a `#` comment. */
export const HASH_GENERATED_COMMENT = `# ${GENERATED_MARK} ${GENERATED_NOTE}`;

/** File the generator writes: the path from the project root with `/`, and the contents. */
export interface GeneratedFile {
  path: string;
  content: string;
}

/**
 * Whether the text carries the generated mark, the current or the former Russian one.
 * @param {string} text File contents.
 * @returns {boolean} true if the generator wrote the file at some point.
 */
export function isGenerated(text: string): boolean {
  return text.includes(GENERATED_MARK) || text.includes(LEGACY_GENERATED_MARK);
}
