// The project's Claude Code files, built from the harness and the project config: thin CLAUDE.md
// files on top of AGENTS.md, role agents, workflow skills, project settings and recording
// publishing. Only the texts live here; sync.ts decides what to do with them on disk.

import {
  RULES_TODO_MARK,
  type Harness,
  type ProjectConfig,
  type StageGuide,
  type StageRole,
  type Workflow,
} from "@cyberzavod/core";
import {
  claudeEffortOf,
  claudeModelOf,
  claudeToolsOf,
  ESCALATION_MODEL,
  GenerateError,
} from "./claude.ts";

/** Mark of a generated file: sync overwrites and deletes such a file itself. */
export const GENERATED_MARK = "Generated by `cyberzavod sync`";

/** Russian mark of versions before 0.8.0: sync recognizes its files in connected projects by it. */
export const LEGACY_GENERATED_MARK = "Сгенерировано `cyberzavod sync`";

const GENERATED_COMMENT = `<!-- ${GENERATED_MARK} from harness and .cyberzavod/project.json: do not edit by hand. Project rules live in AGENTS.md. -->`;

/** File the generator writes: the path from the project root with `/`, and the contents. */
export interface GeneratedFile {
  path: string;
  content: string;
}

/** Adapter templates: texts that are not derived from the harness. */
export interface ClaudeTemplates {
  publishRecording: string;
  recordingEditor: string;
  setup: string;
}

/** Everything the project's Claude Code files are built from. */
export interface ClaudeProject {
  config: ProjectConfig;
  harness: Harness;
  workflow: Workflow;
  /** Directories with AGENTS.md from the project root with `/`; the root is an empty string. */
  rules: string[];
  /** Adapter directories of raw logs and drafts from the project root with `/`. */
  capture: { raw: string; drafts: string };
  /** How to run the Cyberzavod CLI from the project root. */
  cli: string;
  templates: ClaudeTemplates;
}

const RULES_FILE = "AGENTS.md";
const ENTRYPOINT_FILE = "CLAUDE.md";

function joinPath(directory: string, file: string): string {
  return directory === "" ? file : `${directory}/${file}`;
}

function stageGuidesOf(project: ClaudeProject): StageGuide[] {
  return project.workflow.stages.map((stage) => project.harness.stages[stage]);
}

function rootEntrypoint(project: ClaudeProject): string {
  const { config, harness } = project;
  const route = stageGuidesOf(project)
    .map(({ title }) => title)
    .join(" → ");
  const commands = config.verification.commands.map((command) => `- \`${command}\``);
  const verification =
    commands.length === 0
      ? "Project checks are not set: add them to `verification.commands` in `.cyberzavod/project.json`."
      : `Project checks (\`verification.commands\` in \`.cyberzavod/project.json\`) must pass before a commit:\n\n${commands.join("\n")}`;

  return [
    GENERATED_COMMENT,
    "# How to work in this project",
    `The development process is run by Cyberzavod (harness ${config.harness}, workflow \`${config.workflow}\`): ${route}. \`/feature <task>\` takes a task through the whole workflow; stage roles are agents in \`.claude/agents/\`.`,
    verification,
    ...harness.principles.map(({ text }) => text),
    `@${RULES_FILE}`,
  ].join("\n\n");
}

function nestedEntrypoint(): string {
  return `${GENERATED_COMMENT}\n\n@${RULES_FILE}`;
}

function entrypoints(project: ClaudeProject): GeneratedFile[] {
  return project.rules.map((directory) => ({
    path: joinPath(directory, ENTRYPOINT_FILE),
    content: `${directory === "" ? rootEntrypoint(project) : nestedEntrypoint()}\n`,
  }));
}

function agentFile(guide: StageGuide, role: StageRole, model: string): GeneratedFile {
  const content = [
    "---",
    `name: ${role.name}`,
    `description: ${guide.description} The "${guide.title}" stage of /feature.`,
    `tools: ${claudeToolsOf(role.access)}`,
    `model: ${model}`,
    `effort: ${claudeEffortOf(guide.stage)}`,
    "---",
    GENERATED_COMMENT,
    "",
    guide.body,
    "",
  ].join("\n");

  return { path: `.claude/agents/${role.name}.md`, content };
}

function roleAgents(project: ClaudeProject): GeneratedFile[] {
  return stageGuidesOf(project).flatMap((guide) => {
    if (guide.role === undefined) return [];

    const model = claudeModelOf(guide.stage, project.config.agents[guide.stage]);

    return [agentFile(guide, guide.role, model)];
  });
}

function stageRow(guide: StageGuide, project: ClaudeProject): string {
  if (guide.role === undefined) return `| ${guide.title} | the lead itself | — |`;

  const model = claudeModelOf(guide.stage, project.config.agents[guide.stage]);

  return `| ${guide.title} | \`${guide.role.name}\` | ${model} |`;
}

function featureFrontmatter(project: ClaudeProject, guides: readonly StageGuide[]): string {
  const route = guides.map(({ title }) => title.toLowerCase()).join(", ");

  return [
    "---",
    "name: feature",
    `description: Runs a task through the ${project.workflow.name} workflow — ${route}; each role has its own model. Usage: /feature <task>.`,
    "argument-hint: <task>",
    "disable-model-invocation: true",
    "---",
    GENERATED_COMMENT,
  ].join("\n");
}

function stageTable(project: ClaudeProject, guides: readonly StageGuide[]): string {
  return [
    "| Stage | Role | Model |",
    "| --- | --- | --- |",
    ...guides.map((guide) => stageRow(guide, project)),
  ].join("\n");
}

function featureSkill(project: ClaudeProject): GeneratedFile {
  const guides = stageGuidesOf(project);
  const ownStages = guides
    .filter((guide) => guide.role === undefined)
    .map((guide) => `## ${guide.title} stage\n\n${guide.body}`);
  const content = [
    featureFrontmatter(project, guides),
    "# A task through the workflow",
    stageTable(project, guides),
    project.harness.conductor,
    `Stronger model for the second rework — \`${ESCALATION_MODEL}\`: pass \`model: "${ESCALATION_MODEL}"\` in the agent call.`,
    ...ownStages,
  ].join("\n\n");

  return { path: ".claude/skills/feature/SKILL.md", content: `${content}\n` };
}

/**
 * Fills an adapter template with the generated mark, the CLI command, the journal directories and
 * the placeholder mark of the starter AGENTS.md.
 * @param {string} template Template text with `{{generated}}`, `{{cli}}`, `{{raw}}`, `{{drafts}}`,
 * `{{todo}}`.
 * @param {ClaudeProject} project Project.
 * @returns {string} Finished file text.
 * @throws {GenerateError} If the template has a placeholder the adapter does not know.
 */
export function renderTemplate(template: string, project: ClaudeProject): string {
  const values: Record<string, string> = {
    generated: GENERATED_COMMENT,
    cli: project.cli,
    raw: project.capture.raw,
    drafts: project.capture.drafts,
    todo: RULES_TODO_MARK,
  };

  return template.replace(/\{\{(\w+)\}\}/g, (placeholder, name: string) => {
    const value = values[name];

    if (value === undefined) {
      throw new GenerateError((messages) => messages.errors.unknownPlaceholder(placeholder));
    }

    return value;
  });
}

function setupSkill(project: ClaudeProject): GeneratedFile {
  return {
    path: ".claude/skills/setup/SKILL.md",
    content: renderTemplate(project.templates.setup, project),
  };
}

function recordingFiles(project: ClaudeProject): GeneratedFile[] {
  return [
    {
      path: ".claude/skills/publish-recording/SKILL.md",
      content: renderTemplate(project.templates.publishRecording, project),
    },
    {
      path: ".claude/agents/recording-editor.md",
      content: renderTemplate(project.templates.recordingEditor, project),
    },
  ];
}

/**
 * Builds all of the project's Claude Code files except the settings.
 * @param {ClaudeProject} project Config, harness, workflow, rule directories and templates.
 * @returns {GeneratedFile[]} Files by path from the project root.
 * @throws {GenerateError} If a stage is assigned to an agent this adapter does not run.
 */
export function claudeFiles(project: ClaudeProject): GeneratedFile[] {
  return [
    ...entrypoints(project),
    ...roleAgents(project),
    featureSkill(project),
    setupSkill(project),
    ...recordingFiles(project),
  ];
}
